language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch

env:
  - MPLBACKEND="agg"  # for Matplotlib to work on the test environments

install:
  - pip install .[test] codecov

script:
  - check-manifest
  - pytest --cov=fronts

after_success:
  - codecov  # upload coverage results to codecov.io